### ISSUE TITLE
SDS submission

### ISSUE THREAD

**Issue by noyBarak** [RoiZundak/madeJLM-Company#3]

**Comment by noyBarak** [comment]
https://github.com/RoiZundak/madeJLM-Company/wiki/sds
משימה 4 - הגשת מסמך sds 
@ItamarShDev

**Comment by RoiZundak** [comment]
Hi @ItamarShDev & @robi-y 
Can u please close this isuues.

**Comment by RoiZundak** [comment]
Hi @ItamarShDev & @robi-y 
Can u please close this isuues.
