### ISSUE TITLE
Code Review and Code itself

### ISSUE THREAD

**Issue by ItamarShDev** [RoiZundak/madeJLM-Company#45]
@RoiZundak @DavidOhayonSe @moriatu @noyBarak 
Hey there!
I have two questions for you to finalize your grades for iteration 1+2
1. I dont see a code reviews youve done in any of  the files
2. it seems to me that the code in this repository isnt the project's code. is it correct?

**Comment by RoiZundak** [comment]
Dear Itamar.

About the first thing, yeah we didnt do it, if we want, how we do it?
About the second-> the code in the repository is the right code you can see
it under:
https://github.com/RoiZundak/madeJLM-Company
ActiveC (Folder)
V0.1(Folder)

And the code sits there.

BR,
Roi C
ActiveC

2016-06-08 18:14 GMT+03:00 itamar sharify notifications@github.com:

> Hey there!
> I have two questions for you to finalize your grades for iteration 1+2
> 1. I dont see a code reviews youve done in any of the files
> 2. it seems to me that the code in this repository isnt the project's
> code. is it correct?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/RoiZundak/madeJLM-Company/issues/45, or mute the
> thread
> https://github.com/notifications/unsubscribe/AKFOvSEc_eI-V8umNa4QrEhtJ570LIahks5qJtw9gaJpZM4IxEnZ
> .

## 

_בברכה,_
_רועי כהן._
_054-8044784_
