### ISSUE TITLE
Resubmission - Iterations 3+4

### ISSUE THREAD

**Issue by noyBarak** [RoiZundak/madeJLM-Company#60]
היי @ItamarShDev , @robi-y 
תיקנו את איטרציה 4 לפי ההערות שאיתמר נתן לנו:
- תיקון הלינקים בין כל האיטרציות
- הסבר על server side.

בנוסף - באיטרציה 3 לא הבנו על מה ירד לנו כל-כך הרבה נקודות.
בעמודה של ההצגה בכלל לא קיבלנו ניקוד.

פירוט ציוני איטרציה 3:
<img width="998" alt="2016 06 28 17 11 24" src="https://cloud.githubusercontent.com/assets/17567549/16420375/be7e7718-3d59-11e6-9103-61cfb39f6e21.png">

<img width="301" alt="2016 06 28 17 28 02" src="https://cloud.githubusercontent.com/assets/17567549/16420398/d8aa60de-3d59-11e6-9ef5-be78edb9f090.png">

פירוט ציוני איטרציה 4:
<img width="919" alt="2016 06 28 17 55 19" src="https://cloud.githubusercontent.com/assets/17567549/16420405/e675282a-3d59-11e6-98c8-feb90fa82b45.png">

במידה ועדיין האיטרציות לא כפי שרציתם, אודה לכם באם תגידו מה עלינו לתקן. השקענו המון בפרוייקט הזה ואנחנו נשמח שזה יבוא ליידי ביטוי גם בציון. 

תודה רבה,
נוי ברק.

**Comment by ItamarShDev** [comment]
you have 100 on presentation
